-- Daymoment PostgreSQL / Supabase schema. Jalankan sekali di Supabase SQL Editor.
create extension if not exists pgcrypto;

drop view if exists public.invitation_details cascade;
drop view if exists public.order_details cascade;
drop table if exists public.guest_messages cascade;
drop table if exists public.invitation_guests cascade;
drop table if exists public.gift_accounts cascade;
drop table if exists public.invitation_media cascade;
drop table if exists public.payments cascade;
drop table if exists public.invitations cascade;
drop table if exists public.orders cascade;
drop table if exists public.template_packages cascade;
drop table if exists public.templates cascade;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = timezone('utc', now()); return new; end;
$$;

create table public.templates (
  id bigint generated by default as identity primary key, code varchar(50) not null unique,
  name varchar(100) not null, category varchar(50) not null, description varchar(255) not null,
  thumbnail varchar(255), is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now())
);
create table public.template_packages (
  id bigint generated by default as identity primary key, template_id bigint not null references public.templates(id) on delete cascade,
  code varchar(30) not null, name varchar(80) not null, tagline varchar(180) not null, price numeric(12,2) not null default 0,
  gallery_limit smallint not null default 2 check (gallery_limit between 1 and 20), has_music boolean not null default false,
  has_gift boolean not null default false, has_wishes boolean not null default false, sort_order smallint not null default 0,
  is_active boolean not null default true, created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()), unique (template_id, code)
);
create table public.orders (
  id bigint generated by default as identity primary key, order_code varchar(32) not null unique,
  template_id bigint not null references public.templates(id), package_id bigint not null references public.template_packages(id),
  customer_name varchar(120) not null, customer_email varchar(254) not null, customer_phone varchar(24) not null, editor_token varchar(128) not null unique,
  status varchar(24) not null default 'waiting_payment' check (status in ('waiting_payment','editing','published','cancelled')),
  payment_status varchar(24) not null default 'pending' check (payment_status in ('pending','paid','failed','expired','refunded')),
  editor_email_sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now())
);
create table public.invitations (
  id bigint generated by default as identity primary key, order_id bigint not null unique references public.orders(id) on delete cascade,
  slug varchar(120) unique, groom_full_name varchar(150), groom_nickname varchar(80), groom_father varchar(150), groom_mother varchar(150),
  bride_full_name varchar(150), bride_nickname varchar(80), bride_father varchar(150), bride_mother varchar(150),
  akad_date date, akad_start_time time, akad_end_time time, reception_date date, reception_start_time time, reception_end_time time,
  venue_name varchar(180), venue_address text, maps_url varchar(500), love_story text, instagram varchar(100),
  cover_image varchar(255), groom_photo varchar(255), bride_photo varchar(255), music_file varchar(255), music_title varchar(150),
  published_at timestamptz, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now())
);
create table public.invitation_media (
  id bigint generated by default as identity primary key, invitation_id bigint not null references public.invitations(id) on delete cascade,
  file_path varchar(255) not null, sort_order smallint not null default 0, created_at timestamptz not null default timezone('utc', now())
);
create table public.gift_accounts (
  id bigint generated by default as identity primary key, invitation_id bigint not null references public.invitations(id) on delete cascade,
  provider varchar(80) not null, account_number varchar(100) not null, account_name varchar(150) not null, label varchar(100),
  sort_order smallint not null default 0, is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now())
);
create table public.invitation_guests (
  id bigint generated by default as identity primary key, invitation_id bigint not null references public.invitations(id) on delete cascade,
  guest_name varchar(150) not null, salutation varchar(80) not null default 'Bapak/Ibu/Saudara/i', guest_token varchar(64) not null unique,
  created_at timestamptz not null default timezone('utc', now())
);
create table public.guest_messages (
  id bigint generated by default as identity primary key, invitation_id bigint not null references public.invitations(id) on delete cascade,
  guest_name varchar(120) not null, attendance_status varchar(24) not null check (attendance_status in ('attending','not_attending','unsure')),
  guest_count smallint not null default 1 check (guest_count between 1 and 10), message varchar(500) not null,
  is_approved boolean not null default true, created_at timestamptz not null default timezone('utc', now())
);
create table public.payments (
  id bigint generated by default as identity primary key, order_id bigint not null unique references public.orders(id) on delete cascade,
  gateway varchar(50), gateway_order_id varchar(64) unique, transaction_id varchar(120) unique,
  snap_token text, snap_redirect_url text, payment_type varchar(50), amount numeric(12,2) not null default 0,
  status varchar(24) not null default 'pending' check (status in ('pending','paid','failed','expired','refunded')), paid_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now())
);

drop function if exists public.create_daymoment_order(varchar,bigint,bigint,varchar,varchar,varchar,numeric);
drop function if exists public.create_daymoment_order(varchar,bigint,bigint,varchar,varchar,varchar,varchar,numeric);
create function public.create_daymoment_order(
  p_order_code varchar, p_template_id bigint, p_package_id bigint,
  p_customer_name varchar, p_customer_phone varchar, p_customer_email varchar, p_editor_token varchar, p_amount numeric
) returns bigint language plpgsql security definer set search_path = public as $$
declare new_order_id bigint;
begin
  insert into public.orders (order_code,template_id,package_id,customer_name,customer_phone,customer_email,editor_token)
  values (p_order_code,p_template_id,p_package_id,p_customer_name,p_customer_phone,p_customer_email,p_editor_token)
  returning id into new_order_id;
  insert into public.invitations (order_id) values (new_order_id);
  insert into public.payments (order_id,amount) values (new_order_id,p_amount);
  return new_order_id;
end;
$$;
revoke all on function public.create_daymoment_order(varchar,bigint,bigint,varchar,varchar,varchar,varchar,numeric) from public, anon, authenticated;
grant execute on function public.create_daymoment_order(varchar,bigint,bigint,varchar,varchar,varchar,varchar,numeric) to service_role;

create index idx_templates_active on public.templates(is_active);
create index idx_packages_template on public.template_packages(template_id, is_active, sort_order);
create index idx_orders_status on public.orders(status, payment_status);
create index idx_invitations_published on public.invitations(published_at);
create index idx_media_invitation on public.invitation_media(invitation_id, sort_order);
create index idx_gift_invitation on public.gift_accounts(invitation_id, sort_order);
create index idx_guests_invitation on public.invitation_guests(invitation_id, created_at desc);
create index idx_messages_invitation on public.guest_messages(invitation_id, is_approved, created_at desc);

create trigger templates_updated_at before update on public.templates for each row execute function public.set_updated_at();
create trigger packages_updated_at before update on public.template_packages for each row execute function public.set_updated_at();
create trigger orders_updated_at before update on public.orders for each row execute function public.set_updated_at();
create trigger invitations_updated_at before update on public.invitations for each row execute function public.set_updated_at();
create trigger gifts_updated_at before update on public.gift_accounts for each row execute function public.set_updated_at();
create trigger payments_updated_at before update on public.payments for each row execute function public.set_updated_at();

create view public.order_details as
select o.*, t.code template_code, t.name template_name, t.category template_category,
  p.code package_code, p.name package_name, p.price package_price, p.gallery_limit, p.has_music, p.has_gift, p.has_wishes,
  pay.status payment_record_status, pay.gateway, pay.transaction_id, pay.gateway_order_id
from public.orders o join public.templates t on t.id=o.template_id join public.template_packages p on p.id=o.package_id
left join public.payments pay on pay.order_id=o.id;

create view public.invitation_details as
select i.*, o.order_code, o.editor_token, o.status order_status, o.payment_status, o.template_id, o.package_id,
  t.code template_code, t.name template_name, t.category template_category,
  p.code package_code, p.name package_name, p.price package_price, p.gallery_limit, p.has_music, p.has_gift, p.has_wishes
from public.invitations i join public.orders o on o.id=i.order_id join public.templates t on t.id=o.template_id
join public.template_packages p on p.id=o.package_id;

-- Browser tidak mengakses tabel langsung. Worker memakai service-role dan melewati RLS.
alter table public.templates enable row level security;
alter table public.template_packages enable row level security;
alter table public.orders enable row level security;
alter table public.invitations enable row level security;
alter table public.invitation_media enable row level security;
alter table public.gift_accounts enable row level security;
alter table public.invitation_guests enable row level security;
alter table public.guest_messages enable row level security;
alter table public.payments enable row level security;
revoke all on public.order_details from anon, authenticated;
revoke all on public.invitation_details from anon, authenticated;

-- Realtime publik hanya boleh membaca konten undangan yang memang sudah terbit.
create or replace function public.is_published_invitation(p_invitation_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.invitations i join public.orders o on o.id = i.order_id
    where i.id = p_invitation_id and i.published_at is not null and o.status = 'published'
  );
$$;
revoke all on function public.is_published_invitation(bigint) from public;
grant execute on function public.is_published_invitation(bigint) to anon, authenticated, service_role;

create policy public_read_published_invitations on public.invitations for select to anon
using (public.is_published_invitation(id));
create policy public_read_approved_messages on public.guest_messages for select to anon
using (is_approved and public.is_published_invitation(invitation_id));
create policy public_read_published_gifts on public.gift_accounts for select to anon
using (is_active and public.is_published_invitation(invitation_id));
create policy public_read_published_media on public.invitation_media for select to anon
using (public.is_published_invitation(invitation_id));

do $$ begin
  alter publication supabase_realtime add table public.invitations;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.guest_messages;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.gift_accounts;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.invitation_media;
exception when duplicate_object then null; end $$;

-- Izin Data API dibuat eksplisit agar opsi "Automatically expose new tables" aman dimatikan.
grant usage on schema public to service_role, anon;
grant all privileges on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant select on public.order_details, public.invitation_details to service_role;
grant select on public.invitations, public.guest_messages, public.gift_accounts, public.invitation_media to anon;
