import React from 'react';
import { Loading, ErrorState } from '../components/Layout.jsx';
import { mediaUrl } from '../lib/api.js';
import { useBodyClass, useDocumentTitle, useHeadLinks, useLegacyScripts, useRemote } from '../lib/hooks.js';

const providers=['BCA','BRI','BNI','Mandiri','BSI','CIMB Niaga','PermataBank','SeaBank','Jago','GoPay','DANA','OVO','ShopeePay','Lainnya'];
const salutations=['Bapak/Ibu/Saudara/i','Bapak & Ibu','Saudara/i','Keluarga','Teman/Sahabat'];
const TextField=({label,name,value='',full=false,...props})=><label className={`field ${full?'full':''}`}><span>{label}{props.required&&<b> *</b>}</span><input name={name} defaultValue={value||''} {...props}/></label>;

export default function BuilderPage({token}){
  useBodyClass('builder-page'); useDocumentTitle('Editor Undangan — Daymoment');
  useHeadLinks(['/assets/css/app.css','/assets/css/builder.css']);
  const state=useRemote(`/api/editor/${token}`,[token]);
  useLegacyScripts(['/assets/js/builder.js'],!state.loading&&!state.error);
  if(state.loading)return <Loading/>; if(state.error)return <ErrorState error={state.error}/>;
  const {invitation:i,media,giftAccounts,invitees,templates,appUrl}=state.data;
  const galleryLimit=Math.max(1,Number(i.gallery_limit)||2), hasGift=Boolean(i.has_gift),hasMusic=Boolean(i.has_music);
  const paymentCompleted=new URLSearchParams(window.location.search).get('payment')==='success';
  return <div className="builder-shell" id="builderApp" data-token={token} data-csrf="worker-token" data-template={i.template_code} data-gallery-limit={galleryLimit}>
    {paymentCompleted&&<div className="builder-payment-success" role="status"><b>✓ Pembayaran berhasil</b><span>Terima kasih. Editor undanganmu sekarang sudah aktif.</span></div>}
    <div className="builder-topbar"><div><a href="/" className="builder-brand"><img className="brand-logo" src="/assets/images/brand/daymoment-mark.svg" alt=""/><span className="builder-brand-copy"><strong>Daymoment</strong><small>by Daysheet Group</small></span></a><span className="order-label">{i.order_code} · {i.package_name}</span></div><div className="save-state" id="saveState" data-state="saved"><i/><span>Tersimpan</span></div><button type="button" className="button button-secondary change-template-button" data-open-template>Ganti Template</button></div>
    <div className="mobile-builder-tabs" role="tablist"><button type="button" className="active" data-builder-tab="form">Form</button><button type="button" data-builder-tab="preview">Preview</button></div>
    <div className="builder-content"><section className="builder-form-pane" data-builder-pane="form"><div className="builder-progress"><div className="progress-line"><span id="progressBar" style={{width:'11.111%'}}/></div><div className="progress-copy"><span id="stepCaption">Langkah 1 dari 9</span><strong id="stepTitle">Data Pengantin</strong></div></div>
      <form id="invitationForm" autoComplete="off">
        <section className="form-step active" data-step="0" data-title="Data Pengantin"><Intro icon="♡" title="Kenalkan kedua mempelai" copy="Nama panggilan akan menjadi nama utama pada cover undangan."/><Card title="Mempelai pria"><div className="field-grid"><TextField full label="Nama lengkap" name="groom_full_name" maxLength="150" required value={i.groom_full_name} placeholder="Contoh: Andi Pratama"/><TextField label="Nama panggilan" name="groom_nickname" maxLength="80" required value={i.groom_nickname} placeholder="Andi"/></div></Card><Card title="Mempelai wanita"><div className="field-grid"><TextField full label="Nama lengkap" name="bride_full_name" maxLength="150" required value={i.bride_full_name} placeholder="Contoh: Nisa Maharani"/><TextField label="Nama panggilan" name="bride_nickname" maxLength="80" required value={i.bride_nickname} placeholder="Nisa"/></div></Card></section>
        <section className="form-step" data-step="1" data-title="Data Orang Tua"><Intro icon="⌂" title="Nama orang tua" copy="Lengkapi nama ayah dan ibu dari masing-masing mempelai."/><Card title="Orang tua mempelai pria"><div className="field-grid"><TextField label="Nama ayah" name="groom_father" required value={i.groom_father} placeholder="Bapak ..."/><TextField label="Nama ibu" name="groom_mother" required value={i.groom_mother} placeholder="Ibu ..."/></div></Card><Card title="Orang tua mempelai wanita"><div className="field-grid"><TextField label="Nama ayah" name="bride_father" required value={i.bride_father} placeholder="Bapak ..."/><TextField label="Nama ibu" name="bride_mother" required value={i.bride_mother} placeholder="Ibu ..."/></div></Card></section>
        <section className="form-step" data-step="2" data-title="Jadwal Acara"><Intro icon="◫" title="Kapan hari bahagianya?" copy="Isi waktu akad dan resepsi sesuai jadwal yang telah ditentukan."/><EventFields title="Akad Nikah" prefix="akad" invitation={i}/><EventFields title="Resepsi" prefix="reception" invitation={i}/></section>
        <section className="form-step" data-step="3" data-title="Lokasi"><Intro icon="⌖" title="Di mana acaranya?" copy="Bantu tamu menemukan lokasi dengan alamat jelas dan tautan peta."/><Card><div className="field-grid"><TextField full label="Nama gedung atau lokasi" name="venue_name" required value={i.venue_name} placeholder="Contoh: Pendopo Arunika"/><label className="field full"><span>Alamat lengkap <b>*</b></span><textarea name="venue_address" rows="4" maxLength="1500" required defaultValue={i.venue_address||''}/></label><TextField full type="url" label="Link Google Maps" name="maps_url" value={i.maps_url} placeholder="https://maps.google.com/..."/></div></Card></section>
        <section className="form-step" data-step="4" data-title="Cerita dan Foto"><Intro icon="✦" title="Hidupkan ceritamu" copy="Tambahkan cerita singkat dan foto pilihan. Gambar akan dikompres sebelum diunggah."/><Card><label className="field full"><span>Kisah singkat pasangan <b>*</b></span><textarea name="love_story" rows="6" maxLength="3000" required defaultValue={i.love_story||''}/><small><span data-char-count="love_story">0</span>/3000 karakter</small></label><TextField full label="Instagram pasangan (opsional)" name="instagram" value={i.instagram} placeholder="andindanisa"/></Card><UploadCard title="Foto cover" help="Maksimal 2 MB · JPG, PNG, WEBP"><label className="cover-upload"><input type="file" id="coverInput" accept="image/jpeg,image/png,image/webp"/><img id="coverThumb" src={mediaUrl(i.cover_image)} alt="Preview foto cover"/><span><b>Ganti foto cover</b><small>Gambar akan dipotong menyesuaikan desain.</small></span></label></UploadCard><UploadCard title="Foto masing-masing mempelai" help="Dipakai pada profil pria dan wanita di undangan."><div className="couple-photo-editor"><ProfileUpload id="brideInput" thumb="brideThumb" src={mediaUrl(i.bride_photo)} label="Foto wanita"/><ProfileUpload id="groomInput" thumb="groomThumb" src={mediaUrl(i.groom_photo)} label="Foto pria"/></div></UploadCard><div className="form-section-card upload-section"><div className="upload-heading"><div><h2>Galeri</h2><p>Maksimal {galleryLimit} foto sesuai paket {i.package_name}, masing-masing 2 MB</p></div><span id="galleryCount">{media.length}/{galleryLimit}</span></div><div className="gallery-editor" id="galleryEditor">{media.map(photo=><figure data-media-id={photo.id} key={photo.id}><img src={mediaUrl(photo.file_path)} alt="Foto galeri"/><button type="button" data-delete-photo={photo.id}>×</button></figure>)}<label className="gallery-add" id="galleryAdd"><input type="file" id="galleryInput" accept="image/jpeg,image/png,image/webp"/><span>＋</span><small>Tambah foto</small></label></div></div></section>
        {(hasGift||hasMusic)&&<section className="form-step" data-step="5" data-title={hasGift?'Hadiah dan Musik':'Musik'}><Intro icon="♪" title={hasGift?'Amplop digital dan musik':'Musik undangan'} copy={hasGift?'Tambahkan beberapa rekening atau e-wallet, lalu unggah musik latar undangan.':'Unggah musik latar untuk menemani tamu membuka undangan.'}/>{hasGift&&<Card><div className="upload-heading"><div><h2>Rekening hadiah</h2><p>Bisa bank maupun e-wallet, maksimal sepuluh.</p></div><button type="button" className="button button-secondary button-small" id="addGiftAccount">+ Tambah</button></div><div className="gift-account-editor" id="giftAccountEditor">{giftAccounts.map(account=><GiftRow key={account.id} account={account}/>)}</div><div className="empty-editor-note" id="giftEmpty" hidden={giftAccounts.length>0}>Belum ada rekening. Klik “Tambah” untuk membuat amplop digital.</div><button type="button" className="button button-primary" id="saveGiftAccounts">Simpan rekening</button></Card>}{hasMusic&&<UploadCard title="Musik undangan" help="MP3, M4A, OGG, atau WAV · maksimal 12 MB."><label className="music-upload-card"><input type="file" id="musicInput" accept="audio/mpeg,audio/mp4,audio/ogg,audio/wav,.mp3,.m4a,.ogg,.wav"/><span className="music-upload-icon">♪</span><span><b id="musicTitle">{i.music_title||'Pilih musik dari perangkat'}</b><small>Musik diputar melalui tombol musik pada undangan.</small></span></label></UploadCard>}</section>}
        <section className="form-step" data-step="6" data-title="Daftar Tamu"><Intro icon="⌁" title="Buat link untuk setiap tamu" copy="Nama tamu akan langsung tampil pada cover ketika link pribadinya dibuka."/><Card><div className="invitee-create-grid"><label className="field"><span>Sapaan</span><select id="inviteeSalutation">{salutations.map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Nama tamu</span><input id="inviteeName" maxLength="150" placeholder="Contoh: Bapak Budi sekeluarga"/></label><button type="button" className="button button-primary" id="addInvitee">Tambah tamu</button></div></Card><Card><div className="upload-heading"><div><h2>Link undangan personal</h2><p id="inviteeCount">{invitees.length} nama tersimpan</p></div></div><div className="invitee-list" id="inviteeList">{invitees.map(g=><article className="invitee-row" data-guest-id={g.id} data-guest-name={g.guest_name} key={g.id}><div><strong>{g.guest_name}</strong><small>{g.salutation}</small></div><div className="invitee-link"><input readOnly value={`${String(appUrl||location.origin).replace(/\/$/,'')}/${i.slug||'preview-undangan'}?to=${encodeURIComponent(g.guest_name)}`}/><button type="button" data-copy-invitee>Salin</button><button type="button" data-delete-invitee>Hapus</button></div></article>)}</div><div className="empty-editor-note" id="inviteeEmpty" hidden={invitees.length>0}>Belum ada nama tamu. Tambahkan nama untuk mendapatkan link personal.</div></Card></section>
        <section className="form-step" data-step="7" data-title="URL Undangan"><Intro icon="↗" title="Pilih alamat undangan" copy="Buat URL singkat yang mudah diingat dan dibagikan."/><Card><label className="field full"><span>Slug URL <b>*</b></span><div className="url-field"><span>{String(appUrl||location.origin).replace(/\/$/,'')}/</span><input name="slug" maxLength="120" defaultValue={i.slug||''} placeholder="andi-nisa" pattern="[a-z0-9-]+"/></div><small>Hanya huruf kecil, angka, dan tanda hubung.</small><small className="slug-status" id="slugStatus"/><div className="slug-suggestions" id="slugSuggestions"/></label><div className="reserved-note"><strong>Alamat yang tidak tersedia</strong><p>admin, api, assets, media, template, order, payment, edit, publish, dan success.</p></div></Card></section>
        <section className="form-step" data-step="8" data-title="Preview dan Publish"><Intro icon="✓" title="Semua siap untuk diterbitkan" copy="Periksa preview, lengkapi penanda yang belum hijau, lalu terbitkan."/><Card title="Ringkasan kesiapan"><ul id="publishChecklist">{[['couple','Data pengantin dan orang tua'],['event','Jadwal dan lokasi acara'],['story','Cerita pasangan'],['slug','URL undangan unik']].map(v=><li data-check-group={v[0]} key={v[0]}><span>{v[1]}</span><b>Periksa</b></li>)}</ul></Card><div className="locked-copy"><span>🔒</span><div><strong>Teks undangan utama dikunci</strong><p>Salam pembuka, judul bagian, dan teks penutup sudah disiapkan agar tetap rapi dan konsisten.</p></div></div><div className="publish-errors" id="publishErrors" hidden/><button type="button" className="button button-primary button-wide publish-button" id="publishButton">Selesai dan Publish</button><small className="publish-hint">Undangan tetap dapat disunting setelah diterbitkan.</small></section>
      </form><div className="builder-nav"><button type="button" className="button button-secondary" id="prevStep" disabled>← Sebelumnya</button><button type="button" className="button button-primary" id="nextStep">Selanjutnya →</button></div></section>
      <aside className="builder-preview-pane" data-builder-pane="preview"><div className="preview-toolbar"><div><span>Live Preview</span><small id="previewTemplateName">{i.template_name}</small></div><button type="button" data-refresh-preview>↻</button></div><div className="device-frame"><div className="device-notch"/><iframe id="livePreview" title="Live preview undangan" src={`/template/${i.template_code}?embed=1&token=${token}`}/></div><p className="preview-tip">Perubahan form tampil langsung di sini dan disimpan otomatis.</p></aside>
    </div>
    <dialog className="template-dialog" id="templateDialog"><form method="dialog" className="dialog-card"><div className="dialog-heading"><div><span className="eyebrow">Ganti nuansa</span><h2>Pilih template baru</h2><p>Semua data dan foto yang sudah diisi akan tetap tersimpan.</p></div><button value="cancel">×</button></div><div className="dialog-templates">{templates.map(t=><button type="button" className={`dialog-template ${t.code===i.template_code?'selected':''}`} data-template-choice={t.code} data-template-name={t.name} key={t.id}><span className={`dialog-thumb thumb-${t.code}`}><i>{t.name[0]}</i></span><span><b>{t.name}</b><small>{t.category}</small></span><i className="choice-check">✓</i></button>)}</div><div className="dialog-actions"><button value="cancel" className="button button-secondary">Batal</button><button type="button" id="confirmTemplate" className="button button-primary" disabled>Gunakan Template</button></div></form></dialog><div className="toast-region" id="toastRegion"/>
  </div>;
}

function Intro({icon,title,copy}){return <div className="step-intro"><span className="step-icon">{icon}</span><div><h1>{title}</h1><p>{copy}</p></div></div>}
function Card({title,children}){return <div className="form-section-card">{title&&<h2>{title}</h2>}{children}</div>}
function EventFields({title,prefix,invitation}){return <Card title={title}><div className="field-grid"><TextField full type="date" label={`Tanggal ${prefix==='akad'?'akad':'resepsi'}`} name={`${prefix}_date`} required value={invitation[`${prefix}_date`]}/><TextField type="time" label="Jam mulai" name={`${prefix}_start_time`} required value={String(invitation[`${prefix}_start_time`]||'').slice(0,5)}/><TextField type="time" label="Jam selesai" name={`${prefix}_end_time`} required value={String(invitation[`${prefix}_end_time`]||'').slice(0,5)}/></div></Card>}
function UploadCard({title,help,children}){return <div className="form-section-card upload-section"><div className="upload-heading"><div><h2>{title}</h2><p>{help}</p></div></div>{children}</div>}
function ProfileUpload({id,thumb,src,label}){return <label className="cover-upload compact-upload"><input type="file" id={id} accept="image/jpeg,image/png,image/webp"/><img id={thumb} src={src} alt={`Preview ${label}`}/><span><b>{label}</b><small>Klik untuk pilih foto.</small></span></label>}
function GiftRow({account}){return <div className="gift-account-row" data-gift-row><label className="field"><span>Bank / e-wallet</span><select data-gift-field="provider" defaultValue={account.provider}>{providers.map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Nomor rekening / akun</span><input data-gift-field="account_number" maxLength="100" defaultValue={account.account_number}/></label><label className="field"><span>Nama pemilik</span><input data-gift-field="account_name" maxLength="150" defaultValue={account.account_name}/></label><label className="field"><span>Label opsional</span><input data-gift-field="label" maxLength="100" defaultValue={account.label||''}/></label><button type="button" className="remove-editor-row" data-remove-gift>Hapus</button></div>}
