import React from 'react';
import { Layout, Loading, ErrorState } from '../components/Layout.jsx';
import { money } from '../lib/api.js';
import { useRemote } from '../lib/hooks.js';

export default function HomePage() {
  const { data, loading, error } = useRemote('/api/templates');
  return <Layout className="homepage" title="Daymoment — Tempat kisah baik dimulai.">
    <section className="hero"><div className="hero-copy"><span className="eyebrow">Undangan digital, dibuat dengan hati</span><h1>Buat Undangan Pernikahan Digitalmu</h1><p>Ceritakan hari bahagiamu lewat desain yang indah, personal, dan siap dibagikan dalam hitungan menit.</p><div className="hero-actions"><a className="button button-primary" href="#templates">Lihat Pilihan Template</a><a className="text-link" href="#cara-kerja">Pelajari cara kerja <span>→</span></a></div><div className="hero-trust"><span>✓ Live preview</span><span>✓ Mudah disunting</span><span>✓ Ramah ponsel</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="phone-mockup hero-phone"><div className="phone-speaker"/><div className="mini-cover mini-navy"><div className="mini-frame"><span className="mini-kicker">The Wedding of</span><strong>A <i>&amp;</i> N</strong><small>Andi &amp; Nisa</small><span className="mini-button">Buka Undangan</span></div></div></div><div className="floating-note note-one"><span>✦</span> Siap dibagikan</div><div className="floating-note note-two"><span>♡</span> Personal</div></div></section>
    <section className="templates-section" id="templates"><div className="section-heading"><span className="eyebrow">Koleksi baru segera hadir</span><h2>Kita sedang menyiapkan desain pertama</h2><p>Template akan dibangun dan dirilis satu per satu agar setiap detailnya benar-benar matang.</p></div>
      {loading ? <Loading /> : error ? <ErrorState error={error} /> : <div className="template-grid">{!data.templates.length && <div className="template-empty"><span>01</span><h3>Template pertama sedang disiapkan</h3><p>Koleksi lama sudah dikosongkan. Desain baru akan hadir di area ini.</p></div>}{data.templates.map((template, index) => <article className="template-card" key={template.id}><div className={`template-visual visual-${template.code}`}><div className="collection-mini"><span>{String(index + 1).padStart(2, '0')}</span><i/><small>The Wedding of</small><strong>A <em>&amp;</em> N</strong><b>{template.name}</b></div></div><div className="template-card-body"><div className="template-meta"><span>{template.category}</span><span>{template.package_count} paket</span></div><h3>{template.name}</h3><p>{template.description}</p>{template.starting_price && <p className="template-starting-price">Mulai {money(template.starting_price)}</p>}<div className="card-actions"><a className="button button-secondary" href={`/template/${template.code}`}>Lihat Preview</a><a className="button button-primary" href={`/order?template=${template.code}`}>Pilih Template</a></div></div></article>)}</div>}
    </section>
    <section className="steps-section" id="cara-kerja"><div className="section-heading"><span className="eyebrow">Sederhana dari awal sampai tayang</span><h2>Tiga langkah menuju undanganmu</h2></div><div className="steps-grid">{[['01','Pilih nuansa','Tentukan template yang paling mewakili hari bahagiamu.'],['02','Isi ceritamu','Tambahkan data acara, cerita, dan foto sambil melihat hasilnya langsung.'],['03','Terbitkan & bagikan','Dapatkan tautan personal dan kirimkan kepada orang-orang tersayang.']].map((step) => <article key={step[0]}><span className="step-number">{step[0]}</span><div><h3>{step[1]}</h3><p>{step[2]}</p></div></article>)}</div></section>
    <section className="home-cta"><div><span className="eyebrow">Hari istimewamu layak dikenang</span><h2>Mulai ciptakan undangan yang bercerita.</h2></div><a className="button button-light" href="#templates">Pilih Template</a></section>
    <footer className="site-footer"><a className="brand brand-light" href="/"><img className="brand-logo" src="/assets/images/brand/daymoment-mark.svg" alt=""/><span className="brand-copy"><strong>Daymoment</strong><small>by Daysheet Group</small></span></a><p>Dibuat untuk merayakan cerita yang tumbuh menjadi selamanya.</p><small>© {new Date().getFullYear()} Daymoment by Daysheet Group. Semua hak dilindungi.</small></footer>
  </Layout>;
}
