import React, { useMemo } from 'react';
import { Loading, ErrorState } from '../components/Layout.jsx';
import { mediaUrl } from '../lib/api.js';
import { useBodyClass, useDocumentTitle, useHeadLinks, useLegacyScripts, useRemote } from '../lib/hooks.js';
import { useInvitationRealtime } from '../lib/realtime.js';
import LunaraAzureTemplate from '../templates/LunaraAzureTemplate.jsx';

const A='/assets/images/templates/puspa-jawi/';
const TEMPLATE_RUNTIME={
  puspa_jawi:{title:'Puspa Jawi — Daymoment',font:'https://fonts.googleapis.com/css2?family=Italianno&family=Marcellus&family=Manrope:wght@400;500;600&display=swap',css:'/assets/css/templates/puspa-jawi.css?v=20260918-1',script:'/assets/js/templates/puspa-jawi.js'},
  lunara_azure:{title:'Lunara Azure — Daymoment',font:'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600&family=Manrope:wght@400;500;600;700&family=Parisienne&display=swap',css:'/assets/css/templates/lunara-azure.css?v=20260917-6',script:'/assets/js/templates/lunara-azure.js?v=20260917-6'}
};
const MONTHS=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
const DAYS=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'];
const sampleDate=()=>{const d=new Date();d.setDate(d.getDate()+45);return d.toISOString().slice(0,10)};
const sample=(pkg={})=>({id:0,slug:'',groom_full_name:'Andi Pratama',groom_nickname:'Andi',groom_father:'Bapak H. Suryanto',groom_mother:'Ibu Hj. Rahayu',bride_full_name:'Nisa Maharani',bride_nickname:'Nisa',bride_father:'Bapak H. Firmansyah',bride_mother:'Ibu Hj. Lestari',akad_date:sampleDate(),akad_start_time:'08:00',akad_end_time:'10:00',reception_date:sampleDate(),reception_start_time:'11:00',reception_end_time:'14:00',venue_name:'Pendopo Arunika',venue_address:'Jl. Melati No. 12, Yogyakarta',maps_url:'https://maps.google.com/',love_story:'Berawal dari pertemuan sederhana pada sebuah sore di Yogyakarta, percakapan kami tumbuh menjadi persahabatan, lalu keyakinan untuk berjalan bersama.',instagram:'andindanisa',gallery_limit:pkg.gallery_limit||3,has_music:Boolean(pkg.has_music),has_gift:Boolean(pkg.has_gift),has_wishes:Boolean(pkg.has_wishes),music_file:null,...pkg});
const idDate=(value,day=true)=>{const d=new Date(`${value||sampleDate()}T12:00:00`);return `${day?`${DAYS[d.getDay()]}, `:''}${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`};
const timeRange=(start,end)=>`${String(start||'').slice(0,5)}${end?` – ${String(end).slice(0,5)}`:''} WIB`;
const attendance=(v)=>({attending:'Hadir',not_attending:'Tidak Hadir',unsure:'Masih Ragu'}[v]||'Masih Ragu');

export default function InvitationPage({slug,templateCode,preview=false}){
  useBodyClass(preview?'embed-preview':'');
  const query=useMemo(()=>new URLSearchParams(window.location.search),[]), token=query.get('token');
  const path=preview?(token?`/api/editor/${token}`:`/api/templates/${templateCode}`):`/api/invitations/${slug}${window.location.search}`;
  const state=useRemote(path,[path]);
  const activeCode=templateCode||state.data?.invitation?.template_code||state.data?.template?.code||'puspa_jawi';
  const runtime=TEMPLATE_RUNTIME[activeCode]||TEMPLATE_RUNTIME.puspa_jawi;
  useDocumentTitle(runtime.title);
  useHeadLinks([runtime.font,'/assets/css/templates/base.css?v=20260918-1',runtime.css]);
  useLegacyScripts(['/assets/js/preview.js','/assets/js/greeting.js',runtime.script],!state.loading&&!state.error);
  useInvitationRealtime(state.data?.invitation?.id, state.reload, !preview && !state.loading && !state.error);
  if(state.loading)return <Loading/>; if(state.error)return <ErrorState error={state.error}/>;
  let invitation,media=[],giftAccounts=[],greetings=[],guestName='Bapak/Ibu/Saudara/i',guestSalutation='Kepada Yth.';
  if(preview&&!token){const template=state.data.template,pkg=template.packages.find(p=>p.code===(query.get('package')||'signature'))||template.packages[0];invitation=sample({...pkg,package_code:pkg.code,package_name:pkg.name});if(pkg.has_gift)giftAccounts=[{provider:'BCA',account_number:'1234 5678 90',account_name:'Andi & Nisa',label:'Hadiah pernikahan'}];}
  else {invitation=preview?withFallbacks(state.data.invitation):state.data.invitation;media=state.data.media||[];giftAccounts=state.data.giftAccounts||[];greetings=state.data.greetings||[];guestName=state.data.guestName||guestName;guestSalutation=state.data.guestSalutation||guestSalutation;}
  const Template=activeCode==='lunara_azure'?LunaraAzureTemplate:PuspaJawi;
  return <Template invitation={invitation} media={media} giftAccounts={giftAccounts} greetings={greetings} guestName={guestName} guestSalutation={guestSalutation} preview={preview}/>;
}

function withFallbacks(value){const fallback=sample(value);for(const key of Object.keys(fallback)){if(value[key]===null||value[key]===undefined||String(value[key]).trim()==='')value={...value,[key]:fallback[key]};}return value}

function PuspaJawi({invitation:i,media,giftAccounts,greetings,guestName,guestSalutation,preview}){
  const groom=i.groom_nickname||'Andi',bride=i.bride_nickname||'Nisa',limit=Math.max(1,Number(i.gallery_limit)||5),photos=media.slice(0,limit);
  const cover=mediaUrl(i.cover_image),bridePhoto=mediaUrl(i.bride_photo||media[0]?.file_path||i.cover_image),groomPhoto=mediaUrl(i.groom_photo||media[1]?.file_path||i.cover_image);
  const eventDate=i.reception_date||sampleDate(),eventTime=String(i.reception_start_time||'11:00').slice(0,5), calendar=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`Pernikahan ${groom} & ${bride}`)}&dates=${eventDate.replaceAll('-','')}T${eventTime.replace(':','')}00/${eventDate.replaceAll('-','')}T${eventTime.replace(':','')}00&location=${encodeURIComponent(i.venue_name||'')}`;
  return <><Symbols/><div className="invitation-page puspa-jawi" data-template-root data-slug={i.slug||''}>
    <section className="opening-cover jawi-opening-cover" aria-label="Cover undangan"><div className="opening-scenery"/><div className="opening-shade"/><div className="gate-panel gate-left"/><div className="gate-panel gate-right"/><Botanical className="opening-botanical"/><Hanging side="left"/><Hanging side="right"/><div className="opening-copy" data-cover-content><span className="jawi-kicker">The Wedding of</span><h1><span data-live="bride_nickname">{bride}</span><i>&amp;</i><span data-live="groom_nickname">{groom}</span></h1><time data-date-field="reception_date">{idDate(eventDate,false)}</time><div className="opening-guest"><small>{guestSalutation}</small><strong>{guestName}</strong></div><button className="jawi-button open-invitation" type="button" data-open-invitation><span>Buka Undangan</span><Icon name="jawi-arrow"/></button></div></section>
    <main className="invitation-content jawi-layout"><aside className="jawi-stage" aria-label="Latar kisah pasangan"><div className="stage-parallax"/><div className="stage-vignette"/><Botanical className="stage-botanical"/><div className="stage-copy"><small>The Wedding of</small><h2><span data-live="bride_nickname">{bride}</span><i>&amp;</i><span data-live="groom_nickname">{groom}</span></h2><div className="stage-guest"><span>{guestSalutation}</span><strong>{guestName}</strong></div></div><div className="stage-petals">{Array.from({length:5},(_,n)=><i key={n}/>)}</div></aside>
      <div className="jawi-scroll"><section className="jawi-section jawi-prologue"><Botanical className="section-botanical botanical-full"/><div className="prologue-frame jawi-reveal" data-reveal="scale"><span className="jawi-kicker">Pawiwahan</span><h2><span data-live="bride_nickname">{bride}</span> <i>&amp;</i> <span data-live="groom_nickname">{groom}</span></h2><div className="couple-portrait"><img src={cover} alt="Foto pasangan" decoding="async"/><span/></div><p>#{`${bride}${groom}`.replace(/[^A-Za-z0-9]/g,'')}Forever</p></div><Cloud className="floating-cloud prologue-cloud"/></section>
      <section className="jawi-section jawi-greeting"><div className="greeting-floral-frame"><img src={`${A}floral-frame-v2.webp`} alt="" decoding="async"/></div><Cloud className="greeting-cloud greeting-cloud-left"/><Cloud className="greeting-cloud greeting-cloud-right"/><div className="greeting-card jawi-reveal" data-reveal="scale"><div className="greeting-crest"><span/><img src={`${A}gunungan-line.svg`} alt=""/><span/></div><small className="greeting-eyebrow">Atas Rahmat Allah</small><h2>The Wedding</h2><div className="greeting-divider"><i/><b>&amp;</b><i/></div><p className="arabic">السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ</p><p className="greeting-message">Dengan memohon rahmat dan ridho Allah SWT, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan menjadi bagian dari hari bahagia kami.</p><span className="greeting-signature">Pawiwahan · {bride} &amp; {groom}</span></div></section>
      <section className="jawi-section jawi-couple-section"><Person type="bride" photo={bridePhoto} title="Mempelai Wanita" full={i.bride_full_name||'Nisa Maharani'} father={i.bride_father||'Bapak Firmansyah'} mother={i.bride_mother||'Ibu Lestari'}/><div className="couple-connector"><span/><i>&amp;</i><span/></div><Person type="groom" photo={groomPhoto} title="Mempelai Pria" full={i.groom_full_name||'Andi Pratama'} father={i.groom_father||'Bapak Suryanto'} mother={i.groom_mother||'Ibu Rahayu'}/></section>
      <section className="jawi-section jawi-countdown-section"><Cloud className="cloud-title jawi-reveal"/><Heading small="Save the date" title="Hari Yang Ditunggu"/><div className="countdown-wreath jawi-reveal" data-reveal="scale"><img className="countdown-floral" src={`${A}floral-frame-v2.webp`} srcSet={`${A}floral-frame-v2-mobile.webp 900w, ${A}floral-frame-v2.webp 1536w`} sizes="(max-width: 620px) 96vw, 540px" alt="" decoding="async"/><img src={`${A}gunungan-line.svg`} alt=""/><div className="jawi-countdown countdown" data-countdown={`${eventDate}T${eventTime}:00+07:00`}>{[['days','Hari'],['hours','Jam'],['minutes','Menit'],['seconds','Detik']].map(v=><div key={v[0]}><strong {...{[`data-${v[0]}`]:''}}>00</strong><span>{v[1]}</span></div>)}</div></div><a className="jawi-button calendar-link jawi-reveal" href={calendar} target="_blank">Tambah ke Kalender <Icon name="jawi-arrow"/></a></section>
      <section className="jawi-section jawi-events-section"><div className="event-ornaments"><Cloud className="event-cloud cloud-one"/><Cloud className="event-cloud cloud-two"/><img className="event-gunungan gunungan-left" src={`${A}gunungan-line.svg`} alt=""/><img className="event-gunungan gunungan-right" src={`${A}gunungan-line.svg`} alt=""/></div><Heading small="Rangkaian Acara" title="Lokasi & Waktu"/><div className="event-date-lockup jawi-reveal" data-reveal="scale"><span>{idDate(eventDate,false)}</span><strong>{new Date(`${eventDate}T12:00:00`).getDate()}</strong><span>{new Date(`${eventDate}T12:00:00`).getFullYear()}</span></div><EventCard type="akad" invitation={i}/><EventCard type="reception" invitation={i}/></section>
      <section className="jawi-section jawi-story-section"><div className="story-gate jawi-reveal" data-reveal="ink"><Heading small="Kisah Kami" title={<>Berawal, Bertumbuh,<br/>Berlabuh</>}/><p data-live="love_story">{i.love_story||'Berawal dari pertemuan sederhana, tumbuh menjadi persahabatan, lalu keyakinan untuk berjalan bersama.'}</p></div></section>
      <section className="jawi-section jawi-gallery-section"><Heading small="Potret Bahagia" title="Galeri Kisah Kami"/><div className="jawi-gallery-track">{photos.length?photos.map((photo,index)=><figure className="jawi-reveal" data-reveal={index%2?'right':'left'} key={photo.id}><img className="gallery-image" loading="lazy" decoding="async" src={mediaUrl(photo.file_path)} alt={`Momen pasangan ${index+1}`}/><figcaption>Kenangan {String(index+1).padStart(2,'0')}</figcaption></figure>):['Pertemuan','Perjalanan','Lamaran','Hari Bahagia','Selamanya'].slice(0,limit).map((caption,index)=><figure className="gallery-empty jawi-reveal" data-reveal={index%2?'right':'left'} key={caption}><span>{String(index+1).padStart(2,'0')}</span><figcaption>{caption}</figcaption></figure>)}</div></section>
      {i.has_gift&&<GiftSection accounts={giftAccounts}/>} {i.has_wishes&&<RsvpSection invitation={i} guestName={guestName} greetings={greetings} preview={preview}/>}<section className="jawi-section jawi-closing-section"><Botanical className="section-botanical botanical-full botanical-closing"/><div className="closing-gate jawi-reveal" data-reveal="scale"><small>Matur Nuwun</small><h2><span data-live="bride_nickname">{bride}</span><i>&amp;</i><span data-live="groom_nickname">{groom}</span></h2><p>Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir serta memberikan doa restu.</p><time data-date-field="reception_date">{idDate(eventDate,false)}</time>{!preview&&<button className="share-button jawi-button" type="button" data-share data-share-url={`${location.origin}/${i.slug}`}>Bagikan Undangan <Icon name="jawi-arrow"/></button>}</div></section><footer className="template-footer jawi-footer"><div className="template-brand-lockup"><img src="/assets/images/brand/daymoment-mark.svg" alt=""/><strong>Daymoment</strong></div><small>by Daysheet Group</small></footer></div>
    </main>{i.has_music&&i.music_file&&<audio data-wedding-audio loop preload="metadata" src={mediaUrl(i.music_file)}/>} {i.has_music&&<button className="jawi-music" type="button" data-music-controller aria-label="Kontrol musik" aria-pressed="false" title={i.music_title||'Musik undangan'}><Icon name="jawi-music"/></button>}
  </div></>;
}

function Symbols(){return <svg className="jawi-symbols"><defs><symbol id="jawi-arrow" viewBox="0 0 24 24"><path d="M5 12h13m-5-5 5 5-5 5"/></symbol><symbol id="jawi-map" viewBox="0 0 24 24"><path d="M12 21s6-5.4 6-12A6 6 0 0 0 6 9c0 6.6 6 12 6 12Z"/><circle cx="12" cy="9" r="2"/></symbol><symbol id="jawi-copy" viewBox="0 0 24 24"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></symbol><symbol id="jawi-music" viewBox="0 0 24 24"><path d="M9 18V6l10-2v12M9 10l10-2"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="16" r="3"/></symbol></defs></svg>}
function Icon({name}){return <svg><use href={`#${name}`}/></svg>}
function Botanical({className}){return <div className={className} aria-hidden="true"><img className="decor-janur" src={`${A}janur-arch-v2.webp`} srcSet={`${A}janur-arch-v2-mobile.webp 900w, ${A}janur-arch-v2.webp 1536w`} sizes="100vw" alt="" decoding="async"/><img className="decor-floral" src={`${A}floral-frame-v2.webp`} srcSet={`${A}floral-frame-v2-mobile.webp 900w, ${A}floral-frame-v2.webp 1536w`} sizes="100vw" alt="" decoding="async"/></div>}
function Hanging({side}){return <div className={`hanging-ornament hang-${side}`} aria-hidden="true"><i/><i/><i/><i/></div>}
function Cloud({className}){return <img className={className} src={`${A}cloud-line.svg`} alt=""/>}
function Heading({small,title}){return <div className="jawi-heading jawi-reveal"><small>{small}</small><h2>{title}</h2></div>}
function Person({type,photo,title,full,father,mother}){return <article className="jawi-person jawi-reveal" data-reveal={type==='bride'?'left':'right'}><div className={`portrait-frame ${type}-frame`}><img src={photo} alt={`Foto ${title}`} loading="lazy" decoding="async"/><span/></div><small>{title}</small><h2 data-live={`${type}_full_name`}>{full}</h2><p>{type==='bride'?'Putri':'Putra'} dari</p><strong><span data-live={`${type}_father`}>{father}</span><br/>&amp; <span data-live={`${type}_mother`}>{mother}</span></strong></article>}
function EventCard({type,invitation:i}){const akad=type==='akad',date=i[`${type}_date`]||i.reception_date;return <article className={`jawi-event ${akad?'':'reception-event'} jawi-reveal`} data-reveal={akad?'left':'right'}><div className="event-icon"><span/></div><small>{akad?'Sakral & khidmat':'Dengan sukacita'}</small><h3>{akad?'Akad Nikah':'Resepsi'}</h3><time data-date-field={`${type}_date`}>{idDate(date)}</time><strong data-time-range={type}>{timeRange(i[`${type}_start_time`],i[`${type}_end_time`])}</strong><p data-live="venue_name">{i.venue_name||'Lokasi Acara'}</p><address data-live="venue_address">{i.venue_address||'Alamat lengkap akan diumumkan.'}</address><a className="jawi-button" data-live-href="maps_url" href={i.maps_url||'#'} target="_blank"><Icon name="jawi-map"/> Lihat Peta</a></article>}
function GiftSection({accounts}){return <section className="jawi-section jawi-gift-section"><div className="gift-emblem"><img src={`${A}gunungan-line.svg`} alt=""/><span/></div><MovingClouds className="clouds-back"/><div className="gift-inner"><div className="jawi-heading jawi-reveal"><small>Tanda Kasih</small><h2>Wedding Gift</h2><p>Doa restu Anda adalah hadiah terindah. Apabila ingin mengirimkan tanda kasih, dapat melalui rekening berikut.</p></div>{accounts.length?<><div className="bank-picker jawi-reveal" data-bank-picker><input className="bank-picker-toggle" type="checkbox" id="bankPickerToggle"/><label className="bank-picker-summary" htmlFor="bankPickerToggle"><span>Pilih bank / e-wallet</span><strong data-bank-label>{accounts[0].provider}</strong><i/></label><div className="bank-picker-options">{accounts.map((a,index)=><button type="button" data-bank-value={index} aria-pressed={index===0} key={a.id||index}><span>{a.provider}</span>{a.label&&<small>{a.label}</small>}</button>)}</div></div><div className="gift-bank-stack">{accounts.map((a,index)=><div className="bank-card jawi-reveal" data-reveal="scale" data-gift-account-card={index} hidden={index>0} key={a.id||index}><span className="bank-chip"/><small>{a.provider}</small><strong data-account-number>{a.account_number}</strong><p>a.n. {a.account_name}</p>{a.label&&<em>{a.label}</em>}<button type="button" data-copy-account><Icon name="jawi-copy"/> Salin Nomor</button></div>)}</div></>:<div className="gift-empty jawi-reveal">Informasi amplop digital belum ditambahkan.</div>}</div><MovingClouds className="clouds-front"/></section>}
function MovingClouds({className}){return <div className={`moving-clouds ${className}`}><div>{Array.from({length:6},(_,n)=><Cloud key={n}/>)}</div></div>}
function RsvpSection({invitation:i,guestName,greetings,preview}){return <section className="jawi-section jawi-rsvp-section" id="rsvp"><div className="rsvp-ornament rsvp-ornament-left"><Cloud/></div><div className="rsvp-ornament rsvp-ornament-right"><Cloud/></div><div className="rsvp-shell"><div className="rsvp-emblem"><img src={`${A}gunungan-line.svg`} alt=""/></div><Heading small="Ucapan & Harapan" title="Turut Berbahagia"/>{preview&&<p className="preview-form-badge">Mode preview — form tidak mengirim data</p>}<form className="greeting-form jawi-form jawi-reveal" {...(preview?{'data-preview-form':''}:{'data-greeting-form':''})}><input type="hidden" name="slug" value={i.slug||''}/><label><span>Nama</span><input name="guest_name" maxLength="120" required defaultValue={guestName!=='Bapak/Ibu/Saudara/i'?guestName:''} placeholder="Nama Anda"/></label><div className="form-split"><CustomSelect caption="Jumlah tamu" name="guest_count" initial="1" label="1 Orang" options={[[1,'1 Orang'],[2,'2 Orang'],[3,'3 Orang'],[4,'4 Orang']]}/><CustomSelect caption="Kehadiran" name="attendance_status" initial="" label="Pilih kehadiran" options={[["attending",'Hadir'],['not_attending','Tidak Hadir'],['unsure','Masih Ragu']]}/></div><label><span>Ucapan & Doa</span><textarea name="message" maxLength="500" required placeholder="Tuliskan doa hangat..."/><small><span data-message-count>0</span>/500</small></label><button className="jawi-button" type="submit">Kirim Ucapan <Icon name="jawi-arrow"/></button><p className="form-feedback" data-form-feedback/></form><div className="greeting-list jawi-wishes" data-greeting-list>{greetings.length?greetings.map(g=><article className="greeting-item" key={g.id}><div className="greeting-head"><strong>{g.guest_name}</strong><small>{attendance(g.attendance_status)}</small></div><p>{g.message}</p></article>):<div className="greeting-empty" data-empty-greeting>Belum ada ucapan. Jadilah yang pertama mengirimkan doa hangat.</div>}</div></div></section>}
function CustomSelect({caption,name,initial,label,options}){return <div className="jawi-custom-select form-choice" data-custom-select><span className="choice-caption">{caption}</span><input type="hidden" name={name} value={initial} readOnly/><button type="button" className="choice-trigger" data-choice-trigger aria-haspopup="listbox" aria-expanded="false"><span data-choice-label>{label}</span><i/></button><div className="choice-options" data-choice-options role="listbox" hidden>{options.map((v,index)=><button type="button" role="option" data-choice-value={v[0]} aria-selected={index===0&&initial!==''} key={v[0]}>{v[1]}</button>)}</div></div>}
