import React, { useEffect } from 'react';
import { Layout, Loading, ErrorState } from '../components/Layout.jsx';
import { useRemote } from '../lib/hooks.js';

export default function SuccessPage({ token }) {
  const page = Math.max(1, Number(new URLSearchParams(window.location.search).get('page')) || 1);
  const { data, loading, error } = useRemote(`/api/success/${token}?page=${page}`, [token,page]);
  useEffect(() => { const handler=async(e)=>{const button=e.target.closest('[data-copy]');if(!button)return;try{await navigator.clipboard.writeText(button.dataset.copy);window.showToast?.('Tautan berhasil disalin.');}catch{window.prompt('Salin tautan berikut:',button.dataset.copy);}};document.addEventListener('click',handler);return()=>document.removeEventListener('click',handler);},[]);
  if (loading) return <Layout className="success-page"><Loading /></Layout>;
  if (error) return <Layout className="success-page"><ErrorState error={error} /></Layout>;
  const pageStart=Math.max(1,data.guestPage-2), pageEnd=Math.min(data.guestPages,pageStart+4);
  return <Layout className="success-page" title="Undangan Berhasil Diterbitkan — Daymoment"><section className="success-wrap"><div className="success-column"><div className="success-card"><div className="success-check">✓</div><span className="eyebrow">Undanganmu sudah tayang</span><h1>Selamat, undangan berhasil diterbitkan!</h1><p>Salin tautan di bawah lalu bagikan kepada keluarga dan sahabat.</p><div className="url-copy"><span>{data.publicUrl}</span><button type="button" data-copy={data.publicUrl}>Salin URL</button></div><div className="success-actions"><a className="button button-primary" href={`/${data.invitation.slug}`} target="_blank">Buka Undangan</a><a className="button button-secondary" href={`/edit/${token}`}>Kembali ke Editor</a></div><div className="private-warning"><strong>Jaga tautan editor tetap pribadi</strong><p>Siapa pun yang memiliki tautan ini dapat menyunting undanganmu.</p><div className="private-url"><span>{data.editorUrl}</span><button type="button" data-copy={data.editorUrl}>Salin</button></div></div></div><section className="guest-links-card"><div className="guest-links-heading"><div><span className="eyebrow">Tautan personal tamu</span><h2>Bagikan undangan satu per satu</h2><p>Setiap tautan akan menampilkan nama tamu yang dituju.</p></div><strong>{data.guestTotal} tamu</strong></div>{data.invitees.length?<><div className="guest-link-list">{data.invitees.map((guest)=>{const url=`${data.publicUrl}?to=${encodeURIComponent(guest.guest_name)}`;return <article className="guest-link-row" key={guest.id}><div className="guest-link-identity"><strong>{guest.guest_name}</strong><small>{guest.salutation}</small></div><span className="guest-personal-url" title={url}>{url}</span><button type="button" data-copy={url}>Salin</button><a href={url} target="_blank">Buka</a></article>;})}</div>{data.guestPages>1&&<nav className="guest-pagination">{data.guestPage>1&&<a href={`?page=${data.guestPage-1}`}>←</a>}{Array.from({length:pageEnd-pageStart+1},(_,i)=>pageStart+i).map((item)=><a key={item} className={item===data.guestPage?'active':''} href={`?page=${item}`}>{item}</a>)}{data.guestPage<data.guestPages&&<a href={`?page=${data.guestPage+1}`}>→</a>}</nav>}</>:<div className="guest-links-empty">Belum ada nama tamu. Tambahkan daftar tamu melalui editor untuk membuat tautan personal.</div>}</section></div></section></Layout>;
}
